// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos-rest/data-rest.proto

/*
Package proto_data_rest is a generated protocol buffer package.

It is generated from these files:
	protos-rest/data-rest.proto

It has these top-level messages:
	RequestMessage
	ResponseMessage
*/
package proto_data_rest

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RequestMessage struct {
	Content string `protobuf:"bytes,1,opt,name=content" json:"content,omitempty"`
}

func (m *RequestMessage) Reset()                    { *m = RequestMessage{} }
func (m *RequestMessage) String() string            { return proto.CompactTextString(m) }
func (*RequestMessage) ProtoMessage()               {}
func (*RequestMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RequestMessage) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type ResponseMessage struct {
	Content string `protobuf:"bytes,1,opt,name=content" json:"content,omitempty"`
}

func (m *ResponseMessage) Reset()                    { *m = ResponseMessage{} }
func (m *ResponseMessage) String() string            { return proto.CompactTextString(m) }
func (*ResponseMessage) ProtoMessage()               {}
func (*ResponseMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ResponseMessage) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*RequestMessage)(nil), "proto.data.rest.RequestMessage")
	proto.RegisterType((*ResponseMessage)(nil), "proto.data.rest.ResponseMessage")
}

func init() { proto.RegisterFile("protos-rest/data-rest.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 113 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0x2d, 0x4a, 0x2d, 0x2e, 0xd1, 0x4f, 0x49, 0x2c, 0x49, 0x04, 0xb3, 0xf4, 0xc0,
	0xa2, 0x42, 0xfc, 0x60, 0x4a, 0x0f, 0x24, 0xac, 0x07, 0x12, 0x56, 0xd2, 0xe2, 0xe2, 0x0b, 0x4a,
	0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0xf1, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x15, 0x92, 0xe0, 0x62,
	0x4f, 0xce, 0xcf, 0x2b, 0x49, 0xcd, 0x2b, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x71,
	0x95, 0xb4, 0xb9, 0xf8, 0x83, 0x52, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x09, 0x2a, 0x4e, 0x62,
	0x03, 0xdb, 0x64, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x37, 0x78, 0x92, 0xdd, 0x8f, 0x00, 0x00,
	0x00,
}
